name: Gitee前端部署
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 核心修复：使用 npm + 淘宝源 暴力升级 Node
      - name: 暴力升级 Node.js 到 18
        run: |
          echo "升级前 Node 版本："
          node -v

          # 1. 设置淘宝镜像源 (关键！)
          npm config set registry https://registry.npmmirror.com

          # 2. 全局安装 n (Node版本管理工具)
          sudo npm install -g n

          # 3. 强制安装并切换到 Node 18
          sudo n 18

          # 4. 刷新环境变量 (确保当前 shell 能找到新 node)
          hash -r 

          echo "升级后 Node 版本 (必须 >= 18)："
          node -v
          npm -v

      # 3. 安装依赖并打包
      - name: 安装依赖 & 打包
        run: |
          # 再次确保是用淘宝源
          npm config set registry https://registry.npmmirror.com

          # 安装依赖
          npm install

          # 打包
          npm run build

          # 检查产物
          ls -la dist/

      # 4. 上传文件 (SCP)
      - name: 上传 dist 到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: 'dist/*'
          target: '/var/www/html/vue-admin-template/'
          strip_components: 1

      # 5. 重启 Nginx (SSH)
      - name: 修正权限并重启 Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            # 赋予 www-data 权限
            sudo chown -R www-data:www-data /var/www/html/vue-admin-template/
            sudo chmod -R 755 /var/www/html/vue-admin-template/
            # 重载配置
            sudo systemctl reload nginx
            echo "部署完成！"
