name: 前端自动+手动部署
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # 覆盖容器配置（解决Node版本问题）
    container:
      image: ubuntu:22.04 # 用纯净Ubuntu镜像，手动装Node
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 关键：手动安装Node.js 18（替换容器旧版本）
      - name: 安装Node.js 18.x
        run: |
          # 更新系统依赖
          apt update && apt install -y curl wget
          # 安装NodeSource源（稳定版18）
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          # 安装Node.js和npm
          apt install -y nodejs
          # 验证版本（必须≥18）
          node -v
          npm -v

      - name: 安装依赖并打包
        run: |
          # 国内源加速
          npm config set registry https://registry.npmmirror.com
          # 清理缓存
          npm cache clean --force
          # 安装依赖
          npm install --force
          # 先删除旧dist（避免缓存）
          rm -rf ./dist
          # 执行打包（输出详细日志）
          npm run build --verbose
          # 验证dist是否生成
          if [ ! -d "./dist" ]; then
            echo "❌ dist文件夹未生成！"
            exit 1
          fi
          ls -la ./dist/

      - name: 部署到阿里云服务器
        uses: appleboy/ssh-action@master
        if: success() && exists('./dist')
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          scp: |
            ./dist/* ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:/var/www/html/vue-admin-template/
          script: |
            sudo chown -R www-data:www-data /var/www/html/vue-admin-template/
            sudo chmod -R 755 /var/www/html/vue-admin-template/
            sudo systemctl restart nginx
            ls -la /var/www/html/vue-admin-template/
