name: 极速部署(本地已打包)
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码 (包含dist)
        uses: actions/checkout@v4

      - name: 检查 dist
        run: |
          if [ ! -d "./dist" ]; then
            echo "❌ 仓库里没有 dist 文件夹！请在本地打包并提交 dist。"
            exit 1
          fi

      - name: 直接上传
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: 'dist/*'
          target: '/var/www/html/vue-admin-template/'
          strip_components: 1

      - name: 重启 Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: 'sudo systemctl reload nginx'
